dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: winneymj-travis
  on:
    tags: true
  password:
    secure: E6uQLFKV7OdtdkI7FYOwEQbAOrkDM5dEf7ZE88hWy+zkGuy9Frs0/B15PNj3xYukXzHjP/zj4/E0zC0XliijOoPqH72cyiP0UBPszdxOh/34vKwerbiKQAqBAMe7pnc+hWJPUGB5xbpFilKfn6p70d/BKx6ach8tLa1QoFMNmwb7rkcu1BD4uGmCYAM20/hWj+uP9H1DfytPfzkbx6hSZwfqCM2a7BafVbK99t3bWZqjN9u/VRm/+ZtcwM6jBAfoUa4W0QWlrwhX+VaAdmaG8tlHhTCscdTqkj1C2ibRRQEBoUvnAGijlO9rVbEfTb10410Jlzd/0xoQhSdA4Sb1qUsdhFWWWoLY2juX5ZTxaH7uChwYB02iWyrDCH1YQjFqgSIz/ua8OafkUPrvILwsexO7yAz4Mc7/P/WqMFpS38hPbT7qf0Yv9Y2AX5xiAHk1bdRBu2rloxckz6YV1x27ioJgPIrrLYVmiFbasNKQpm6zFISDwobBModiys+Z9Tbm0m6WTpYTxAvb0sox0S/DMz2RqldXZf4R0aN/pp6SNYk/ast7ef1nR1CRxp7svtmjhAr8ptLniOFMxF1wTYL94hXYBWgT4kdip9AAwJclZsfrszF2hEqZVadcEzygpt+h/Hye/fCoXB2hcxRfomgkbjcfVZ69wWD40lILbXiI718=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint sh1106.py
- circuitpython-build-bundles --filename_prefix circuitpython-sh1106 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
